Entity40\Reservation:
  type: entity
  table: reservas
  indexes:
    reservas_pkey:
      columns: [id]
  id:
    id:
      type: integer
      generator:
        strategy: SEQUENCE
      sequenceGenerator:
        sequenceName: reserva_ai
        allocationSize: 100
        initialValue: 1
  fields:
    arrival:
      type: date
      column: llegada
    duration:
      type: integer
      column: duracion
    payment_method:
      type: string
      column: medio_pago
  manyToOne:
    hotel:
      targetEntity: Entity40\Hotel
      inversedBy: reservations
      joinColumn:
        name: hotel_id
        referencedColumnName: id
    guest:
      targetEntity: Entity40\Guest
      inversedBy: reservation
      joinColumn:
        name: huesped_id
        referencedColumnName: id
  oneToMany:
    facilityUses:
      targetEntity: Entity40\FacilityUse
      mappedBy: reservation
  oneToOne:
    review:
      targetEntity: Entity40\Review
      inversedBy: reservation
      joinColumn:
        name: critica_id
        referencedColumnName: id
