Entity40\Guest:
  type: entity
  table: huespedes
  indexes:
    huespedes_pkey:
      columns: [id]
  id:
    id:
      type: integer
      generator:
        strategy: SEQUENCE
      sequenceGenerator:
        sequenceName: huesped_ai
        allocationSize: 100
        initialValue: 1
  fields:
    name:
      type: string
      column: nombre
    phone_number:
      type: string
      column: nro_telefono
    identity_number:
      type: string
      column: identificacion
    birthdate:
      type: date
      column: fecha_nacimiento
  oneToMany:
    reservations:
      targetEntity: Entity40\Reservation
      mappedBy: huesped_id
      cascade: ["persist", "merge"]
