Entity37\Reservation:
  type: entity
  table: reserva
  indexes:
    reserva_pkey:
      columns: [idreserva]
  id:
    id:
      type: integer
      column: idreserva
      generator:
        strategy: SEQUENCE
      sequenceGenerator:
        sequenceName: reserva_idreserva_seq
        allocationSize: 100
        initialValue: 1
  fields:
    date:
      type: date
      column: fecha
    time:
      type: time
      column: hora
    quantity:
      type: integer
      column: cantidad
  oneToOne:
    restaurantReservation:
      targetEntity: Entity37\ReservationRestaurant
      mappedBy: reservation
